// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import { defineConfig } from 'prisma/config';
import { config } from 'dotenv';

// Load environment variables from the root .env file
config({ path: '/workspaces/autoestudo_sgpe/.env' });

// Build DATABASE_URL from individual environment variables
const dbUser = process.env.DB_USER;
const dbPassword = process.env.DB_PASSWORD;
const dbName = process.env.DB_NAME;
const dbPort = process.env.DB_PORT || '5432';

if (!dbUser || !dbPassword || !dbName) {
  throw new Error('Missing required database environment variables: DB_USER, DB_PASSWORD, DB_NAME');
}

const databaseUrl = `postgresql://${dbUser}:${dbPassword}@localhost:${dbPort}/${dbName}?schema=public`;

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: databaseUrl,
  },
});
